FROM node:14
ENV NODE_ENV=localhost
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

# copies all application code into the container
COPY . .
EXPOSE 8080

RUN chown -R node /usr/src/app
USER node
CMD ["npm", "start"]
